name: Notify Discord

on:
  push:
  pull_request:
  issues:
  release:
    types: [published, created]

jobs:
  discord-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub-Discord Bridge
        uses: gkr0110/github-discord-bridge@v1.0.2
        with:
          webhook_dev: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          webhook_alerts: ${{ secrets.DISCORD_WEBHOOK_ALERTS }}
          webhook_announcements: ${{ secrets.DISCORD_WEBHOOK_ANNOUNCEMENTS }}
